# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    serializer:
        serialize_null: true
    zone:
        - { path: ^/game/* }
    view:
        mime_types:
            json: ['application/json']
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/game', priorities: [json], fallback_format: ~, prefer_extension: false }
    exception:
        enabled: false
    body_listener: true
    param_fetcher_listener: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    routing_loader:
        default_format: json
        include_format: false
